/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Test1 } from "./Test1";
export type { Test2 } from "./Test2";

export { Test1__factory } from "./factories/Test1__factory";
export { Test2__factory } from "./factories/Test2__factory";
