/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface Test1Interface extends ethers.utils.Interface {
  functions: {
    "thisIsNonPayableFunction(uint256)": FunctionFragment;
    "thisIsPayableFunction()": FunctionFragment;
    "thisIsPureFunction()": FunctionFragment;
    "thisIsViewFunction(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "thisIsNonPayableFunction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "thisIsPayableFunction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "thisIsPureFunction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "thisIsViewFunction",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "thisIsNonPayableFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thisIsPayableFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thisIsPureFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thisIsViewFunction",
    data: BytesLike
  ): Result;

  events: {};
}

export class Test1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: Test1Interface;

  functions: {
    thisIsNonPayableFunction(
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    thisIsPayableFunction(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    thisIsPureFunction(overrides?: CallOverrides): Promise<[BigNumber]>;

    thisIsViewFunction(
      mul: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  thisIsNonPayableFunction(
    added: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  thisIsPayableFunction(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  thisIsPureFunction(overrides?: CallOverrides): Promise<BigNumber>;

  thisIsViewFunction(
    mul: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    thisIsNonPayableFunction(
      added: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    thisIsPayableFunction(overrides?: CallOverrides): Promise<void>;

    thisIsPureFunction(overrides?: CallOverrides): Promise<BigNumber>;

    thisIsViewFunction(
      mul: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    thisIsNonPayableFunction(
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    thisIsPayableFunction(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    thisIsPureFunction(overrides?: CallOverrides): Promise<BigNumber>;

    thisIsViewFunction(
      mul: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    thisIsNonPayableFunction(
      added: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    thisIsPayableFunction(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    thisIsPureFunction(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    thisIsViewFunction(
      mul: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
